# Generated by Django 6.0.6 on 2026-06-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_brand_image_alter_category_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('In Stock', 'in_stock'), ('Low Stock', 'low_stock'), ('Out Of Stock', 'out_of_stock')], default='in_stock', max_length=20),
        ),
    ]
