# Generated by Django 6.0.6 on 2026-06-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('In Stock', 'in_stock'), ('Low Stock', 'low_stock'), ('Out Of Stock', 'out_of_stock')], default='In Stock', max_length=20),
        ),
    ]
