# Generated by Django 6.0.6 on 2026-06-18 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_blog_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='status',
            field=models.CharField(choices=[('Draft', 'in_draft,'), ('Published', 'in_published')], default='Published', max_length=20),
        ),
    ]
