# Generated by Django 6.0.6 on 2026-06-18 10:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_gallerycategory_blog_created_at_blog_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='marketing.gallerycategory'),
        ),
    ]
