# Generated by Django 6.0.6 on 2026-06-19 07:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_client'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('Description', models.TextField()),
                ('validDate', models.DateField()),
                ('offerImage', models.ImageField(upload_to='Media/Offer')),
                ('createdAt', models.DateTimeField(default=django.utils.timezone.now)),
                ('updatedAt', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offer',
            },
        ),
        migrations.CreateModel(
            name='OfferPamphlets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('link', models.TextField()),
                ('orderPriority', models.IntegerField()),
                ('image', models.ImageField(upload_to='Media/OfferPamphlets')),
            ],
            options={
                'verbose_name': 'Offer Pamphlets',
                'verbose_name_plural': 'Offer Pamphlets',
            },
        ),
    ]
