# Generated by Django 6.0.5 on 2026-06-03 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_order_orderitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(help_text="URL-friendly string (e.g., 'best-kitchenware-for-new-cafes')", unique=True)),
                ('summary', models.TextField(help_text='A short teaser text shown on the main blog grid page.')),
                ('content', models.TextField(help_text='The main body text of your article.')),
                ('cover_image', models.ImageField(upload_to='blog/covers/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text="e.g., 'Momo Hub Complete Kitchen Setup'", max_length=200)),
                ('location', models.CharField(help_text="e.g., 'Itahari' or 'Dharan'", max_length=150)),
                ('image', models.ImageField(upload_to='gallery/setups/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
